[package]
name = "deps"
version = "0.1.0"
authors = ["Yorex Ai"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.3.2"
rayon = "1.5.0"
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
native-tls = "0.2.7"
url = "2.2.2"
bincode = "1.3.3"
